# Generated by Django 5.0 on 2024-01-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_onetimepassword_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptionCode',
            field=models.CharField(default='', max_length=256, verbose_name='Subscription Code'),
        ),
    ]
