# Generated by Django 5.0 on 2024-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_subscriptioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscriptionCode',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Subscription Code'),
        ),
    ]
