# Generated by Django 5.0 on 2024-01-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_phone_number_alter_user_subscriptioncode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
