# Generated by Django 5.0 on 2024-02-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_email_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
