# Generated by Django 5.0 on 2024-01-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlanType', models.CharField(default='silver', max_length=50)),
                ('PlanCode', models.CharField(max_length=256)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
