# Generated by Django 5.0 on 2024-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='interval',
            field=models.CharField(choices=[('hourly', 'hourly'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('quarterly', 'quarterly'), ('biannually', 'biannually'), ('annually', 'annually')], default='hourly', max_length=20),
        ),
    ]
