# Generated by Django 5.0 on 2024-01-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionplans_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplans',
            name='PlaneName',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
