# Generated by Django 5.0 on 2024-01-18 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscriptionplans_planename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplans',
            options={'verbose_name': 'SubscriptionPlan', 'verbose_name_plural': 'SubscriptionPlans'},
        ),
    ]
