# Generated by Django 5.0 on 2024-02-06 12:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
