# Generated by Django 5.0 on 2024-02-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notifications_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
    ]
